/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int POINTS = 5;
  /** RegularExpression Id. */
  int SEMICOLON = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int OPPAREN = 9;
  /** RegularExpression Id. */
  int CLSPAREN = 10;
  /** RegularExpression Id. */
  int FUNCTION = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int REAL = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int ENDVAR = 16;
  /** RegularExpression Id. */
  int CODE = 17;
  /** RegularExpression Id. */
  int ENDCODE = 18;
  /** RegularExpression Id. */
  int IS = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int IDENT = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int DIGITS = 23;
  /** RegularExpression Id. */
  int VLSTRING = 24;
  /** RegularExpression Id. */
  int VLNUM = 25;
  /** RegularExpression Id. */
  int FLOAT = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\":\"",
    "\";\"",
    "\"+\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"function\"",
    "\"integer\"",
    "\"string\"",
    "\"real\"",
    "\"var\"",
    "\"endvar\"",
    "\"code\"",
    "\"endcode\"",
    "\"is\"",
    "\"return\"",
    "<IDENT>",
    "<LETTER>",
    "<DIGITS>",
    "<VLSTRING>",
    "<VLNUM>",
    "<FLOAT>",
  };

}
